---

version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    versioning-strategy: lockfile-only

  - package-ecosystem: bundler
    directory: /test/rails_60
    schedule:
      interval: daily
    versioning-strategy: lockfile-only

  - package-ecosystem: bundler
    directory: /test/rails_61
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
