branches:
  only:
    - master

language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.16.0

gemfile:
  - test/gemfiles/Gemfile-Rails-4-2
  - test/gemfiles/Gemfile-Rails-5-0
  - test/gemfiles/Gemfile-Rails-5-1
  - Gemfile

before_install:
  - rm "${BUNDLE_GEMFILE}.lock"

matrix:
  fast_finish: true

  allow_failures:
    - rvm: jruby-9.1.16.0
