language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby-9.0.5.0
  - rbx-2.2.10
gemfile:
  - test/gemfiles/Gemfile-Rails-3-2
  - test/gemfiles/Gemfile-Rails-4-0
  - test/gemfiles/Gemfile-Rails-4-1
  - test/gemfiles/Gemfile-Rails-4-2
