---

version: 2.1

.install_bundler: &install_bundler
  run:
    name: Install a specific bundler version
    command: gem install bundler -v 2.0.2

.copy_current_gemfile: &copy_current_gemfile
  run:
    name: Cat current Gemfile to a specific file so caching works
    command: cat "$BUNDLE_GEMFILE.lock" > current_gemfile.lock

.restore_cache: &restore_cache
  restore_cache:
    keys:
      - bundler-dependencies-{{ checksum "current_gemfile.lock" }}-{{ .Environment.CIRCLE_JOB }}

.install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: bundle install --path /home/circleci/project/vendor/bundle --retry 3 --jobs 3

.save_cache: &save_cache
  save_cache:
    key: bundler-dependencies-{{ checksum "current_gemfile.lock" }}-{{ .Environment.CIRCLE_JOB }}
    paths:
      - vendor/bundle

.check_gemfiles: &check_gemfiles
  run:
    name: Make sure gemfiles are up to date
    command: bundle exec ruby -Itest -e 'require "gemfiles/lint.rb"; Minitest.run'

.check_gemspec: &check_gemspec
  run:
    name: Make sure gemspec builds without warnings
    command: bundle exec ruby -Itest -e 'require "gemfiles/gemspec_lint.rb"; Minitest.run'

.run_tests: &run_tests
  run:
    name: Run tests
    command: bundle exec rake test TESTOPTS="--verbose"

.test_steps: &test_steps
  - checkout
  - *install_bundler
  - *copy_current_gemfile
  - *restore_cache
  - *install_dependencies
  - *save_cache
  - *check_gemfiles
  - *check_gemspec
  - *run_tests

jobs:
  ruby24rails50:
    docker:
      - image: circleci/ruby:2.4.5

    environment:
      BUNDLE_GEMFILE: test/rails_50/Gemfile

    steps:
      *test_steps

  ruby24rails51:
    docker:
      - image: circleci/ruby:2.4.5

    environment:
      BUNDLE_GEMFILE: test/rails_51/Gemfile

    steps:
      *test_steps

  ruby24rails52:
    docker:
      - image: circleci/ruby:2.4.5

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  ruby25rails50:
    docker:
      - image: circleci/ruby:2.5.3

    environment:
      BUNDLE_GEMFILE: test/rails_50/Gemfile

    steps:
      *test_steps

  ruby25rails51:
    docker:
      - image: circleci/ruby:2.5.3

    environment:
      BUNDLE_GEMFILE: test/rails_51/Gemfile

    steps:
      *test_steps

  ruby25rails52:
    docker:
      - image: circleci/ruby:2.5.3

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  ruby25rails60:
    docker:
    - image: circleci/ruby:2.5.3

    environment:
      BUNDLE_GEMFILE: test/rails_60/Gemfile

    steps:
      *test_steps

  ruby26rails50:
    docker:
      - image: circleci/ruby:2.6.1

    environment:
      BUNDLE_GEMFILE: test/rails_50/Gemfile

    steps:
      *test_steps

  ruby26rails51:
    docker:
      - image: circleci/ruby:2.6.1

    environment:
      BUNDLE_GEMFILE: test/rails_51/Gemfile

    steps:
      *test_steps

  ruby26rails52:
    docker:
      - image: circleci/ruby:2.6.1

    environment:
      BUNDLE_GEMFILE: Gemfile

    steps:
      *test_steps

  ruby26rails60:
    docker:
      - image: circleci/ruby:2.6.1

    environment:
      BUNDLE_GEMFILE: test/rails_60/Gemfile

    steps:
      *test_steps

  jruby92rails50:
    docker:
      - image: circleci/jruby:9.2.6.0

    environment:
      BUNDLE_GEMFILE: test/rails_50/Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby92rails51:
    docker:
      - image: circleci/jruby:9.2.6.0

    environment:
      BUNDLE_GEMFILE: test/rails_51/Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby92rails52:
    docker:
      - image: circleci/jruby:9.2.6.0

    environment:
      BUNDLE_GEMFILE: Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

  jruby92rails60:
    docker:
      - image: circleci/jruby:9.2.6.0

    environment:
      BUNDLE_GEMFILE: test/rails_60/Gemfile
      JRUBY_OPTS: -J-Xmx1024m --dev --debug

    steps:
      *test_steps

workflows:
  version: 2

  build:
    jobs:
      # Ruby 2.4
      - ruby24rails50
      - ruby24rails51
      - ruby24rails52

      # Ruby 2.5
      - ruby25rails50
      - ruby25rails51
      - ruby25rails52
      - ruby25rails60

      # Ruby 2.6
      - ruby26rails50
      - ruby26rails51
      - ruby26rails52
      - ruby26rails60

      # JRuby 9.2.0
      - jruby92rails50
      - jruby92rails51
      - jruby92rails52
      - jruby92rails60
